### ISSUE TITLE
Flaky Test: solana-cli::program test_cli_program_extend_program

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#1173]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/018d9c41-e725-794a-9f40-92ba0b42789b)

**Comment by yihau** [comment]
should be fixed by https://github.com/anza-xyz/agave/pull/1115. I will close this one if it remains 100% reliable for 7 days.

btw, it looks quite good after the PR get merged!
<img width="498" alt="Screenshot 2024-05-03 at 22 38 21" src="https://github.com/anza-xyz/agave/assets/8209234/91377335-7845-40a4-b8d8-792cb2320c9e">

**Comment by yihau** [comment]
<img width="1190" alt="Screenshot 2024-05-11 at 01 29 44" src="https://github.com/anza-xyz/agave/assets/8209234/6bd419dc-9ade-4b9f-b986-c15f71e200df">
