### ISSUE TITLE
Flaky Test: solana-local-cluster::local_cluster test_local_cluster_signature_subscribe

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#1560]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/018f5e6b-309b-77f7-aea8-c44eb98ca262)

**Comment by CriesofCarrots** [comment]
This test failure no longer reproduces for me locally on bulk runs, and buildkite analytics show the test as reliable over the last 28 days.
Based on the [last test-failure log](https://buildkite.com/anza/agave/builds/5363#018fde91-a858-401a-9da8-e732e0c548d0), I think it was most likely fixed by chained merkle root work, perhaps https://github.com/anza-xyz/agave/pull/1057
