### ISSUE TITLE
Upgrade program at mainnet-beta always fails with error `invalid account data for instruction`

### ISSUE THREAD

**Issue by jasl** [anza-xyz/agave#1811]
#### Problem

I'm trying to upgrade our program on `mainnet-beta`

Command `solana program deploy target/deploy/dephy_id_program.so --program-id ~/.priv/dephy_id_mainnet.json --verbose`

I've tried the default QUIC and paid RPC node.

I have tried more than 10 times, It always fails with the same error:
`Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction [3 log messages]`

I've tried Solana v1.18.15 and v1.18.17 both had the same result.

I can't reproduce on `solana-test-validator`, it seems that only occur on `mainnet-beta`

**Comment by joncinque** [comment]
This is likely an issue with your program using a syscall that isn't enabled on mainnet. The 2.0 tools will contain a check to make this issue clearer to users with https://github.com/anza-xyz/agave/pull/1654

Marking completed since this is clearer with the next release. If you have any other questions, please ask on the Solana Stack Exchange https://solana.stackexchange.com/
