### ISSUE TITLE
Installing cli using curl isn't returning correct stable version

### ISSUE THREAD

**Issue by heyAyushh** [anza-xyz/agave#2017]
Executing command to install solana
```
sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
```
Results in 
```
downloading stable installer
  ✨ stable commit d0ed878 initialized
 ```
 ```
 solana -V
solana-cli 1.17.25 (src:d0ed878d; feat:3580551090, client:SolanaLabs)
 ```

but when executing [channel_info.sh](https://github.com/anza-xyz/agave/blob/master/ci/channel-info.sh)
stable version is printed as `v1.18.17`

Even `solana-install` cli returns `v1.17.25`
```
solana-install init stable
```

**Comment by willhickey** [comment]
This is caused by the [move to Agave](https://github.com/anza-xyz/agave/wiki/Agave-Transition). We no longer do channel builds from this repo. `solana-install` will still work until the end of v1.18 but only if you give it an explicit release number like this: `solana-install init v1.18.18`

The solution is to switch to Agave and use `agave-install`. There are migration details [on the Agave wiki](https://github.com/anza-xyz/agave/wiki/Agave-Transition), but this is a good start:
`sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"`
