### ISSUE TITLE
Reload identity in metrics after running set-identity command

### ISSUE THREAD

**Issue by stefiix92** [anza-xyz/agave#2332]
#### Problem
When the validator service starts with "unstaked" identity keypair, it seems to be loaded into metrics tags. However, after running `solana-validator set-identity ...` it won't change. As I don't restart the service with "staked" identity, seems like I'm not pushing any metrics into metrics.solana.com

#### Proposed Solution
When running `solana-validator set-identity`, reload metrics tags or module.

**Comment by steviez** [comment]
I see you closed the issue so I'm not sure if you thought this wasn't working or if you actuall observed it not working. Regardless, I believe identity transitions should result in updated metrics ID due to this line:
https://github.com/anza-xyz/agave/blob/9eee2f66775291a1ec4c4b1be32efc1d314002f7/validator/src/admin_rpc_service.rs#L731

**Comment by stefiix92** [comment]
Yeah, I closed it because the metrics are uploaded; Grafana just wasn't showing my identity key from the dropdown. When pasting it there manually, metrics are displayed.
