### ISSUE TITLE
primordial_accounts_file with more than 200M SOL results in bad genesis

### ISSUE THREAD

**Issue by ptaffet-jump** [anza-xyz/agave#338]
#### Problem
If the cumulative balance in a `primordial_accounts_file` is more than about 165,000,000 SOL, then the balance of the `one thanks` account computed [here](https://github.com/anza-xyz/agave/blob/0f8f8cd9706f869f05153c22f3d26507b27f2c6f/genesis/src/genesis_accounts.rs#L266) is 0.  The [computation](https://github.com/anza-xyz/agave/blob/0f8f8cd9706f869f05153c22f3d26507b27f2c6f/genesis/src/stakes.rs#L79) of `stakes_lamports` in `create_and_add_stakes` then underflows, resulting in an account having a balance of nearly `2^64` lamports.  This causes sporadic panics when running the chain because capitalization overflows.

#### Proposed Solution
I don't understand the purpose of the `one thanks` "community" account. Is it still needed? Is there a reason its balance needs to be computed that way?

**Comment by steviez** [comment]
Hi @ptaffet-jump - what branch / commit are you working off of ? We had a similar realization that these accounts should not be getting added to our development clusters when making a new genesis: https://github.com/solana-labs/solana/pull/35266.

Also, the computation underflowing probably explains this issue that we didn't dig further into: https://github.com/anza-xyz/agave/issues/19

Seeing as I don't anticipate re-genesis'ing any of mnb/testnet/devnet, I think the issue is unlikely to be seen again. But, using saturating math to avoid the underflow is probably still worth a quick change

**Comment by ptaffet-jump** [comment]
Ah yes, we were using something based off of 1.17.20, so that's probably too old to get your fix. We'll keep our patch until we update our branch. Thanks!

**Comment by steviez** [comment]
> Ah yes, we were using something based off of 1.17.20, so that's probably too old to get your fix.

Correct, that change will first appear in the 2.0.0 branch. This isn't something we'd typically try to backport, so if y'all are good to go with a patch, I think that is the move
