### ISSUE TITLE
test-validator: Cloned program data accounts don't work as expected

### ISSUE THREAD

**Issue by acheroncrypto** [anza-xyz/agave#522]
### Problem

This is similar to https://github.com/anza-xyz/agave/issues/436 — which was fixed by https://github.com/anza-xyz/agave/pull/501 — however, the fix only includes programs that are cloned using the `--clone-upgradeable-program` option. If an account is cloned using `--clone` — which is what Anchor [does](https://github.com/coral-xyz/anchor/blob/c66b3232938186623c535cec8deba6b98353420b/cli/src/lib.rs#L3292-L3340) — the problem of not being able to interact with the programs still persist. Anchor can switch to use `--clone-upgradeable-program` but it will still be broken on all existing Anchor versions.

### Solution

Always set deployment slot of cloned program data accounts to `0`.

**Comment by jacobcreech** [comment]
@joncinque  Any reason not to do the proposed solution? This is one I'm considering bountying out for devex improvements.

**Comment by joncinque** [comment]
The solution requires special-casing program data accounts during `--clone`, which is redundant because that's special-cased with `--clone-upgradeable-program`, and people should use that instead.

On the flipside, I can't think of a situation where someone would actually want the deployment slot for a program on their `solana-test-validator`. If they do need it, they can setup more specific test fixtures for their use-case. So yep, I think we can include this!

At the same time, Anchor should probably switch to `--clone-upgradeable-program`.
